### PR TITLE
Improve styling

### PR DESCRIPTION
**Pull request by pragyamittal0**
image

### CODE REVIEW

**Review by apoorvpandey0 — CHANGES_REQUESTED** [review]
Screenshot (32)
Hi, the app looks cool, but its opening like this on my desktop, can you please make this a bit bigger in size?
Also you'll need to check the merge conflicts as we merged some other PR's
Thanks.

**Comment by pragyamittal0** [comment]
Done changes!!
image
image

**Comment by pragyamittal0** [comment]
Done changes..
image

**Review by meinhoonharsh — CHANGES_REQUESTED** [review]
Its all perfect, but the code flow of the program has been changed because different components had been created
It would be great if you fetch the master and synchronize your PR after Resolving Conflicts

**Comment by pragyamittal0** [comment]
> Its all perfect, but the code flow of the program has been changed because different components had been created It would be great if you fetch the master and synchronize your PR after Resolving Conflicts

How to do that.. fetch and synchronize

**Comment by apoorvpandey0** [comment]
> > Its all perfect, but the code flow of the program has been changed because different components had been created It would be great if you fetch the master and synchronize your PR after Resolving Conflicts
> 
> How to do that.. fetch and synchronize

```
$ npm run build
6:18:21 PM: > react@1.0.0 build
6:18:21 PM: > react-scripts build
6:18:23 PM: Creating an optimized production build...
6:18:28 PM: Failed to compile.
6:18:28 PM: 
6:18:28 PM: ./src/App.js
6:18:28 PM: SyntaxError: /opt/build/repo/src/App.js: Identifier 'TodoList' has already been declared. (38:9)
6:18:28 PM:   36 |
6:18:28 PM:   37 |
6:18:28 PM: > 38 | function TodoList(props) {
6:18:28 PM:      |          ^
6:18:28 PM:   39 |   console.log(props);
6:18:28 PM:   40 |   var todos = props.todos;
6:18:28 PM:   41 |
6:18:28 PM: ​
6:18:28 PM: ────────────────────────────────────────────────────────────────
6:18:28 PM:   "build.command" failed                                        
6:18:28 PM: ────────────────────────────────────────────────────────────────
6:18:28 PM: ​
6:18:28 PM:   Error message
6:18:28 PM:   Command failed with exit code 1: npm run build
6:18:28 PM: ​
6:18:28 PM:   Error location
6:18:28 PM:   In Build command from Netlify app:
6:18:28 PM:   npm run build
6:18:28 PM: ​
6:18:28 PM:   Resolved config
6:18:28 PM:   build:
6:18:28 PM:     command: npm run build
6:18:28 PM:     commandOrigin: ui
6:18:28 PM:     environment:
6:18:28 PM:       - REVIEW_ID
6:18:28 PM:     publish: /opt/build/repo/build
6:18:28 PM:     publishOrigin: ui
6:18:28 PM: Caching artifacts
```
I have got this log from netlify, can you understand the issue? @pragyamittal0

**Comment by pragyamittal0** [comment]
> > > Its all perfect, but the code flow of the program has been changed because different components had been created It would be great if you fetch the master and synchronize your PR after Resolving Conflicts
> > 
> > 
> > How to do that.. fetch and synchronize
> 
> ```
> $ npm run build
> 6:18:21 PM: > react@1.0.0 build
> 6:18:21 PM: > react-scripts build
> 6:18:23 PM: Creating an optimized production build...
> 6:18:28 PM: Failed to compile.
> 6:18:28 PM: 
> 6:18:28 PM: ./src/App.js
> 6:18:28 PM: SyntaxError: /opt/build/repo/src/App.js: Identifier 'TodoList' has already been declared. (38:9)
> 6:18:28 PM:   36 |
> 6:18:28 PM:   37 |
> 6:18:28 PM: > 38 | function TodoList(props) {
> 6:18:28 PM:      |          ^
> 6:18:28 PM:   39 |   console.log(props);
> 6:18:28 PM:   40 |   var todos = props.todos;
> 6:18:28 PM:   41 |
> 6:18:28 PM: ​
> 6:18:28 PM: ────────────────────────────────────────────────────────────────
> 6:18:28 PM:   "build.command" failed                                        
> 6:18:28 PM: ────────────────────────────────────────────────────────────────
> 6:18:28 PM: ​
> 6:18:28 PM:   Error message
> 6:18:28 PM:   Command failed with exit code 1: npm run build
> 6:18:28 PM: ​
> 6:18:28 PM:   Error location
> 6:18:28 PM:   In Build command from Netlify app:
> 6:18:28 PM:   npm run build
> 6:18:28 PM: ​
> 6:18:28 PM:   Resolved config
> 6:18:28 PM:   build:
> 6:18:28 PM:     command: npm run build
> 6:18:28 PM:     commandOrigin: ui
> 6:18:28 PM:     environment:
> 6:18:28 PM:       - REVIEW_ID
> 6:18:28 PM:     publish: /opt/build/repo/build
> 6:18:28 PM:     publishOrigin: ui
> 6:18:28 PM: Caching artifacts
> ```
> 
> I have got this log from netlify, can you understand the issue? @pragyamittal0

No, but if it's possible then deploy it again by deleting the previous one..
 function TodoList(props) {
> 6:18:28 PM:      |          ^
> 6:18:28 PM:   39 |   console.log(props);
> 6:18:28 PM:   40 |   var todos = props.todos;
I haven't made any changes on this part

**Pull request closed without merging**
